<?php


namespace D9ify\Utility;

use Symfony\Component\Serializer\Normalizer\CustomNormalizer;

class ComposerPropertyNormalizer extends CustomNormalizer
{

    public function normalize(
        $object,
        string $format = null,
        array $context = []
    ) {
    }

    public function denormalize(
        $data,
        string $type,
        string $format = null,
        array $context = []
    ) {
        return parent::denormalize(
            $data,
            $type,
            $format,
            $context
        ); // TODO: Change the autogenerated stub
    }
}
